name: dishfinder
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules # Prevent host node_modules from overwriting container's
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1 # Ensures print statements appear in logs immediately